### ISSUE TITLE
all the documents in CouchDB have conflict issues

### ISSUE THREAD

**Issue by arinef** [alexcorvi/apexo#123]
**Describe the bug**
I noticed that all the documents in CouchDB have conflict issues. 

**To Reproduce**
1. Login to "Apexo" using online version 3.2.0 "couchdb userName and password"
2. Click on 'Staff' or 'patients'
3. Create new "Doctore" or "patients" > but you have to type multiple characters so you noticed the conflict, as more you type as more conflict you get in "CouchDB"
4. now go to CouchDB "Fauxton" project 
5- try to visit the new document added for our patient or doctor   

**Expected behavior**
A new Document added with no conflict

**Actual ** 
the document appears with many conflicts, this was not happening in the older version of apexo  

**Screenshots**

![conflicts](https://user-images.githubusercontent.com/51496889/59137312-e2358e00-898f-11e9-8f61-1157d8ec8b19.jpg)
![conflict](https://user-images.githubusercontent.com/51496889/59137322-e8c40580-898f-11e9-85c5-5fd34c5aaaf7.PNG)

**Comment by alexcorvi** [comment]
Thanks for the feedback, it should be solved now.
Though I must discourage you from using the testing branch.
