### ISSUE TITLE
adding new staff not working with clean Database

### ISSUE THREAD

**Issue by arinef** [alexcorvi/apexo#124]
**Describe the bug**
I am using your last build in "Testing" branch, the app does not work properly with a clean "DataBase" it won't add new staff until I add one manually in "CouchDB" 

**To Reproduce**
1. Delete all the "data" folder inside your "CouchDB"
2. login to "Apexo" using CouchDB username and password
3. Apexo will ask you to "Register as a new staff member" > enter any name

**Expected behavior**
the doctor name should be added to the database and the app will work normally

**Actual **
the doctor name will not be added to the database and the web will show almost empty dashboard

**Screenshots**
![new staff](https://user-images.githubusercontent.com/51496889/59138350-4149d180-8995-11e9-9ee7-a32fe803f6f7.PNG)
![clean app](https://user-images.githubusercontent.com/51496889/59138286-ea43fc80-8994-11e9-940c-69563faa76a3.PNG)
![new Doctor](https://user-images.githubusercontent.com/51496889/59138290-ed3eed00-8994-11e9-94fc-243a038e39e1.jpg)

Note: but if I added the first doctor directly from the database then I go again to the staff page and add new one will work normally

**Comment by alexcorvi** [comment]
Solved! thanks for the feedback

**Comment by arinef** [comment]
Hi Alex, thank you for your response, but the issue still not resolved at my computer, here is the reproduce steps in another way::
1- clear browser cache.
2- navigate to "Apexo" app
3- click on "No Server Mode" button at the bottom left
4- enter any name and press "Register"

Note this should register the user  at the local PouchDB but it's not 

**Screen Shots**
![no server mode](https://user-images.githubusercontent.com/51496889/59150595-94bc2e00-8a2e-11e9-9dac-08c0ffea149c.png)
![Register](https://user-images.githubusercontent.com/51496889/59150599-98e84b80-8a2e-11e9-9401-cc619e73a6ec.png)
![dashboard](https://user-images.githubusercontent.com/51496889/59150603-9be33c00-8a2e-11e9-8609-a8a86eb37256.png)

**Comment by alexcorvi** [comment]
This should be fixed now
