### ISSUE TITLE
"view Sorted Table" UI Broken for "Dental History"

### ISSUE THREAD

**Issue by arinef** [alexcorvi/apexo#127]
I congratulate you for your new design, its stunning, and sorry for posting many issues but I really like "Apexo", and it would be very nice for this to come without any errors,

almost forgot to post the screenshot for the main issue
**Screenshot**
![UI Broken](https://user-images.githubusercontent.com/51496889/59151541-77429080-8a3d-11e9-93a8-6a360dead6f9.png)

and I would like to ask when is version 4 is about to come??

**Comment by alexcorvi** [comment]
fixed, and version 4 is nearly done, check the status at the pinned issue
