### ISSUE TITLE
Arabic language layout issues

### ISSUE THREAD

**Issue by fadiKhalil2** [alexcorvi/apexo#128]
**Describe the bug**
some layout is broken while using the Arabic Language like:
1- part of some characters are hidden.
2- wrong alignment at some field. 
I attached three images to illustrate this:

![Ar Issue](https://user-images.githubusercontent.com/51833353/59528329-a433ef00-8ee6-11e9-97f7-fc5f567805e5.jpg)

![Ar Issue2](https://user-images.githubusercontent.com/51833353/59528339-abf39380-8ee6-11e9-8b9b-9f67917409fa.jpg)

![Ar Issue3](https://user-images.githubusercontent.com/51833353/59542703-d279f480-8f0f-11e9-9cb3-e31359ab3f0d.jpg)

**Comment by alexcorvi** [comment]
Solved in 4.0
