### ISSUE TITLE
clicking td to open appointment

### ISSUE THREAD

**Issue by arinef** [alexcorvi/apexo#129]
Hi Alex, I would like to ask if it's possible to implement this, once the doctor clicks on an appointment in the patient page or orthodontic page it opens details page of the clicked appointment

![appointment1](https://user-images.githubusercontent.com/51496889/59567382-02430c80-9076-11e9-93b0-e6c77ca0a797.png)

![apointment2](https://user-images.githubusercontent.com/51496889/59567386-066f2a00-9076-11e9-97d9-0083db141345.png)

**Comment by alexcorvi** [comment]
Good idea, coming in version 4!
