### ISSUE TITLE
login page stuck at "Compacting databases"

### ISSUE THREAD

**Issue by tifanyArcs** [alexcorvi/apexo#137]
Hi Alix, I faced an issue while I was testing your last commit, "abdbfa99178396157cdaf47a49e83f634c616159"  > "Update login.tsx". 
I tried it on my android mobile it's working fine with a very nice spinner showing a clear text indication, but what happens is this, 
1- I logged in using my CouchDB credential and, then I kept my browser page opened and leave the phone for about 1 hour.
2- when I came back, I tried to open the browser again, once I opened it, it starts to resyncing and showing the indicator for a new session or reopening an old session (without asking me to enter my credential again). but it stuck at "Compacting databases"
3- you know in "mobile chrome" there is no developer tool, so I used the debugger tool to see the console error,
4- when I connect it to my computer I noticed that it shows > 
`app.js:1 POST http://localhost:5984/patients/_compact 401 (Unauthorized)`
`Uncaught (in promise) {error: "unauthorized", reason: "You are not a server or db admin.", status: 401, name: "unauthorized", message: "You are not a server or db admin."}`

this error in the console shows for all modules "treatments, doctors, ...." 
I solved this issue by clearing my browser history then logging again, but it happens again with me, after a while
It seems that the userName and password is not persistent in local browser storage

**Comment by alexcorvi** [comment]
Fixed in the last commit.
