### ISSUE TITLE
login page stuck at "Compacting databases" - Reproduce Steps

### ISSUE THREAD

**Issue by fretAxe** [alexcorvi/apexo#138]
Hi Alex, to reproduce the last issue use the following steps:
1- log in using CouchDB credentials.
2- open developer tools and go-to cookies.
3- remove the "Auth" cookies OR wait for (10 min) without touching the browser page. which  is the time left to expire this cookies.
4- try to refresh the page >> the page will be stuck at "Compacting databases" 

Note: if we haven't removed the cookie it will refresh normally without asking us to enter the credential again.

to illustrate the issue, please see the following images:
![aa](https://user-images.githubusercontent.com/54038823/62887306-a4fdcb80-bd45-11e9-912d-5161fca0091c.png)
Then
![bb](https://user-images.githubusercontent.com/54038823/62887328-adee9d00-bd45-11e9-90ee-71f3745216f6.png)
Issue 
![cc](https://user-images.githubusercontent.com/54038823/62887342-b7780500-bd45-11e9-97af-63d0aea2f3a2.png)

**Comment by fretAxe** [comment]
I think it was asking the user to enter his credentials again if the session end or removed, before the last commit

**Comment by alexcorvi** [comment]
Thank you for reporting this issue.

The application decided to use the active hash (the one it uses when the server is offline) to login, while the database transactions (resync, compact ... etc) can not use this hash.

I've fixed it.

> P.S. the 10 minutes mark at which the cookie expires is a configuration you can change in the CouchDB configs: couch_httpd_auth > timeout (enter expiration timeout in seconds, default is 600 which is 10 minutes).

> P.S. I've also fixed the Arabic letters from being covered by a white layer in the layout.
