### ISSUE TITLE
cancel footer modal cause dismiss to the opened side appointments

### ISSUE THREAD

**Issue by mohamadRoc** [alexcorvi/apexo#168]
after update the UI Fabric, if you click on cancel or any place on the screen while the footer modal is open this will close all the open modals.

instead it should keep the appointments modal open after clicking on cancel or any part of the page

![cancel footer modals](https://user-images.githubusercontent.com/69094075/89112208-068fdc00-d468-11ea-8501-63eb195e9019.PNG)

**Comment by alexcorvi** [comment]
[Fixed in 4.0.1](https://github.com/alexcorvi/apexo/blob/master/CHANGELOG.md#401)
