### ISSUE TITLE
multi console errors once you select Arabic language

### ISSUE THREAD

**Issue by mohamadRoc** [alexcorvi/apexo#171]
**Describe the bug**
console shows 
`Error: [mobx] An invariant failed`
once you select the Arabic language

**To Reproduce**
1. Login to "web.apexo.app"
2. Click on 'Settings'
3. open console
4. the system should be in English at first login.
5. select "Arabic" Language
6. see the errors in the console

**Expected behavior**
A clear console

**Screenshots**
![console errors](https://user-images.githubusercontent.com/69094075/89184398-65a53c00-d5a1-11ea-9a4e-f9b49aac450f.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 84

**Comment by alexcorvi** [comment]
[Fixed in 4.0.1](https://github.com/alexcorvi/apexo/blob/master/CHANGELOG.md#401)
