### ISSUE TITLE
 can't find "../secrets"

### ISSUE THREAD

**Issue by rossanodr** [alexcorvi/apexo#182]
Hey, what's the 'secrets' file to import the dropbox token? I can't find it

import { dropboxAccessToken } from "../secrets"
file.test.ts file in the core folder

**Comment by romanobarassi** [comment]
Same problem.

`ERROR in /Users/.../apexo/src/core/services/files.test.ts
[tsl] ERROR in /Users/.../apexo/src/core/services/files.test.ts(1,36)
      TS2307: Cannot find module '../../secrets'.`

I created a Dropbox access token but I don't know where I can place it.
