### ISSUE TITLE
Add to CORS to docs

### ISSUE THREAD

**Issue by AlhasanIQ** [alexcorvi/apexo#23]
Add a hint in the documentation about CORS as it costed me a painful hour till i could figure out a clean solution. (internet > nginx proxy > docker couchdb)

this is tool very recommended :
https://github.com/pouchdb/add-cors-to-couchdb

**Comment by alexcorvi** [comment]
done, but I've included a link on how to do it using the fauxton web GUI, for two reasons:
- Fauxton comes bundled already with the CouchDB and it doesn't need NPM, Node like the CLI tool you linked.
- The philosophy of CouchDB is a database for the web, so it should be accessed and managed using HTTP requests, and not CLI tools.
