### ISSUE TITLE
This is awesome. Any mobile version on the way?

### ISSUE THREAD

**Issue by naltun** [alexcorvi/apexo#37]
Congrats on the project. This is _really_ cool, although I am in no way affiliated with any healthcare profession.

That being said, after seeing the demo, I'd love to see this used more often. With that, are you looking to expand the supported platforms?

**Comment by alexcorvi** [comment]
I'm supporting browsers as much as possible, and it's a PWA, I think this is sufficient, at least for now.

**Comment by naltun** [comment]
I like it. Thanks for the update.
