### ISSUE TITLE
Login Pin is not working

### ISSUE THREAD

**Issue by abhimalu** [alexcorvi/apexo#41]
Hi Alex,

A great module you have created in here. I am still learning on the React and came across your project.
I tried installing on a server while accessing from desktop and got it working. Although I see a problem with respect to the "Login Pin" that you can set for the first user. Below steps to replicate the issue:
1. Update the "Login Pin"
2. Refresh the app.
3. Database now shows update pin against the user.
4. Logout from the pp for that user.
5. Login for same user and it gets stuck there.

I believe this login pin would be a security measure so that only admin can assign rights to other staff members?

**Comment by alexcorvi** [comment]
Hi, So I tried the steps you described to reproduce the bug and I failed to do so.

So just to make things more clear, is the following what you describe as being stuck:

1. You enter the server host, the user, and password for CouchDB
2. After successfully logging in, you click on a staff member name
3. the application prompts you to enter the PIN for that staff member, but it doesn't accept the PIN you entered

??

**Comment by abhimalu** [comment]
Hey Alex,

Thanks for your response.
The login PIN works on the web app.

But when I try to use the app locally with same server configuration, the
text box for login PIN does not show up.

Meanwhile, your app has a great potential and I am trying to implement it
in one my cousin's dental practice, here in UK. :)
I do need to get the data migration from their previous system into the
Cloudant database.

I am building up a Python script module that will help doing this.
In case anyone is looking for it, let me know and I would love to share. :)

Thanks,
Abhishek

**Comment by alexcorvi** [comment]
Thanks for the followup, this will be fixed in the next release

**Comment by alexcorvi** [comment]
Version 3.0.0 released fixing this issue.
