### ISSUE TITLE
Problem uploading images

### ISSUE THREAD

**Issue by FBernuy** [alexcorvi/apexo#58]
Hello!

I'm having problems uploading images to the patient. When I click on the "Add Image" button of a patient, I select the image and then nothing happens. I realized that the console of the web-app throws an "unauthorized" error, saying that I am not an admin.

![image](https://user-images.githubusercontent.com/13875097/55125900-ff292780-50e9-11e9-8e5b-863a840145e4.png)

On the coachDB I only have admin users, so I don't know what am I doing wrong. Any suggestion?

I am using a local coachDB and using both the web app and the executable.

Thanks!

**Comment by alexcorvi** [comment]
Yeah, it's a bug, but the file uploading/downloading system will be changed in the next release, all files (images, orthodontic records, and backups) will be saved to Dropbox.

The next release will be out in a few days.

**Comment by FBernuy** [comment]
Awesome, thanks!

**Comment by alexcorvi** [comment]
Version 3.0.0 released fixing this issue.
