### ISSUE TITLE
Appointment time not showing when selected.

### ISSUE THREAD

**Issue by FBernuy** [alexcorvi/apexo#61]
**Describe the bug**
When creating or editing an existing appointment the time is set using a slider, but the actual time doesn't show, making it hard to select.

**To Reproduce**
1. Go to appointments
2. Click on any existing appointment
3. Move the 'Time' slider.
4. You can't see the appointment time.

**Expected behavior**
The time should appear near the slider

**Screenshots**
![image](https://user-images.githubusercontent.com/13875097/55519444-3b123e80-564e-11e9-9a4b-c77aa830c77f.png)

**Desktop (please complete the following information):**
 - OS: macOS, WIN10
 - Browser chrome and app
 - Version idk

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by alexcorvi** [comment]
Solved in 3.0.2
