### ISSUE TITLE
Cephalometric analysis window size bug

### ISSUE THREAD

**Issue by FBernuy** [alexcorvi/apexo#62]
**Describe the bug**
The cephalometric window uses only a small section of the window, making it almost impossible to use. The used section can be scrolled, but it is too small for usage.

**To Reproduce**
1. On the Orthodontic tab, go to the Gallery and X-Rays of any patient.
2. Click on an existing analysis o create a new one.
3. When the Analysis window appears, only a small upper section is used.

**Expected behavior**
The analysis should use the whole window.

**Screenshots**
![image](https://user-images.githubusercontent.com/13875097/55519702-4ade5280-564f-11e9-81d9-cf9aecbe70fb.png)

**Desktop (please complete the following information):**
 - OS: macOS, WIN10
 - Browser chrome
 - Version: idk

**Additional context**
Not tested on the demo app as the analysis is not available due to the lack of dropbox configuration.

**Comment by alexcorvi** [comment]
I wasn't able to reproduce this bug, but I made some adjustments that might solve it, please check

**Comment by FBernuy** [comment]
Fixed! Thanks!
