### ISSUE TITLE
Modify DB structure

### ISSUE THREAD

**Issue by EmmanuelAcuna** [alexcorvi/apexo#81]
Hi Alex, I wold like to know if there is a easy way to change the DB structure in order to save appointments, doctors, orthodontic... no as individuals databases but as memebers of a single DB,
for example:
```
MyDB: {
doctors: {..},
appointments: {...},
orthodontic: {...}
...
}
```
Thanks <3``

**Comment by alexcorvi** [comment]
Whatever the reason for such configuration, it's not very efficient. and here are the reasons behind this:

- You need to construct documents and views correctly, so only relevant data will appear in the queries, this requires some server configuration and creation of _design documents, which is something I'd like to avoid. Views, though curcial in some CouchDB applications, are painful part of CouchDB.
- Even if we did go with this route, from my understanding of CouchDB it will gravely affect performance, as every time the _design documents of the database is updated, the views have to be regenerated. So upgrading to a new version of the application that implements a different _design document might take hours. This is not something you would like to have for an application that implements automatic enforced updates like this one.
- As per this application specifically. it has been engineered in a way that respects data type separation, so each *module* has a different data type (think of appointments as a module, patients as a module and so on), and each module can sync, update, and replicate independently.

So to answer your question:
- Is it possible? definitly yes!
- Is it practical? probably not!
- Is there an easy way? I can't think of one.

Anyway, why would you want to do that? what are you trying to acheive? I might be able to help you.

**Comment by EmmanuelAcuna** [comment]
Alex, Thanks in advance!!
..I would like to have an instance of Apexo running with a preconfigured server and instead of the current login I would like to have a doctors login and at the moment their do the Sign in the system take the data from the clinic the doctor belong to.
I know is a little bit different architecture but I dont know if is possible.. or what is the rigth path to do that, thanks!!

**Comment by alexcorvi** [comment]
This is very much applicable, but you're going to face one problem. currently, the application takes a hash of the following details:
- Server location
- Username
- Password
```ts
Md5.hashStr(server + username + password)
```
This hash is being used (among other uses) as a secret key for encrypting/decrypting the local databases. So the problem you'll face is when a user logs out and another user logs in, the hash will change thus the local database will be unreadable (can't be decrypted correctly) and you would have to delete all local databases and sync from the server once again, so the data can be encrypted/decrypted using the new hash . So once again you'll be facing a scenario where performance will be gravely affected!

If you're OK with this, then you should consider reading through [PouchDB-authentication API](https://github.com/pouchdb-community/pouchdb-authentication/blob/master/docs/api.md), and implement the following actions:

- `db.signUpAdmin()` when a new staff member is created
- `db.deleteAdmin()` when a new staff member is deleted
- `db.changePassword()` when a staff member changes their password
- `db.changeUsername()` when a staff member changes their username

**Comment by EmmanuelAcuna** [comment]
Thank U !!
I think that what I goin to do is keep an preconfigured server(serverUrl, user, pass, without sigIOut) and create a new login for doctors, and implement a system of primary keys where every related data have the same key, also modify every data function to get only the data related...
I was wondering if you are interested in work with Us, this is for a client of mine so of course is a pay work, I understand that this is no place to talk about this but is the fastest way, anyway, In case your interest pleace let know, tahnk you.
Congrats for what you did with Apexo, it is a great work!!

**Comment by alexcorvi** [comment]
You're welcome!
Thanks for the offer but I'm currently on a tight schedule.
