### ISSUE TITLE
"Apexo" for multiple clinics

### ISSUE THREAD

**Issue by MohamadZyoud** [alexcorvi/apexo#85]
Hello Alex:
the part I am interested in is CouchDB and PouchDB is there any way to make CouchDB serve multiple users with separate DB (couch_peruser), in your case different clinics, each one has to log in with (username and password) and can only see the related information to that clinic. and How many users (Clinics) this architecture can serve, is there a way to build scalable Back End with only CouchDB, I read a lot of articles about this but I couldn't find any helpful article, can you advise me, I would appreciate your help.

Thank you,

**Comment by alexcorvi** [comment]
This can be done couchDB wise, using design documents, filters and such, but it would be really challenging to integrate it in the application itself.
It's currently serving a single clinic with multiple doctors (staff members), it can't serve a single doctor with multiple clinics unless the DB structure and the UI are re-designed to serve such purpose.
