### ISSUE TITLE
Displays a summary of appointments when selecting a day and prevent user from selecting a predefined time

### ISSUE THREAD

**Issue by wiliamzaklan** [alexcorvi/apexo#99]
When booking a new appointment or modifying an existing one, displays a summary of appointments for the chosen day and prevents the user from choosing a predefined timing. (disable the already taken slots)

**Comment by alexcorvi** [comment]
The application can not use appointment "slots", as it defines a starting time and no ending time. This is to give a bit more liberty for the doctor to set a different time for each appointment
